apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: malware-logs-pvc
  labels:
    app: malware-detector
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
